---
title: "GeneSLand"
author: "Erik Bot"
date: "2024-01-24"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{GeneSLand}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(GeneSLand)
```

```{r style, echo = FALSE, results = 'asis'}
library(BiocStyle)
```

```{r, echo = FALSE}
library(knitr)
```

Defining a sample bulk RNA seq object

```{r}
set.seed(123)
n_profiles <- 50
n_genes <- 5000
counts <- matrix(runif(n_genes*n_profiles,1,10), ncol = n_profiles)
colnames(counts) <- paste0('Cell-', seq(1,dim(counts)[2]))
rownames(counts) <- paste0('Gene-', seq(1,dim(counts)[1]))
```

Now create the SSCE

```{r, results='hide', message=FALSE}
ssce <- createSSCE(xProfiles = counts)
```

Now plot the 2D landscape

```{r}
plotSSCE(ssce)
# AUC
plotSSCE(ssce, values = 'AUC')
# dRate
plotSSCE(ssce, values = 'dRate')
# lbSpec
plotSSCE(ssce, values = 'lbSpec')
```

Now plot specific lines

```{r}
plot_lines_SSCE(ssce, gene = 'Gene-1')
plot_multiple_lines_SSCE(ssce, genes = c('Gene-1', 'Gene-2'))
```

Do the same for gene groups

```{r}
gene_groups <- split(rownames(counts), sample(LETTERS, nrow(counts), replace = TRUE))
ssce_groups <- createSSCE(counts, geneGroups = gene_groups, nRand = 20)
```

If you want to add the scores significance or the intra-group variability after creating the SSCE, 
you can:

```{r}
ssce_groups <- compute_significance_SSCE(ssce_groups)
ssce_groups <- compute_variability_SSCE(ssce_groups)
```

Now plot specific lines

```{r}
plot_lines_SSCE(ssce_groups, gene = 'Z')
plot_multiple_lines_SSCE(ssce_groups, genes = c('Z', 'A'))
```

```{r}
sessionInfo()
```

